### ISSUE TITLE
Code Review for Rosario

### ISSUE THREAD

**Issue by Valerio-SirLance** [PUP-BSIT/ex9-sixth_sense#1]
Hello! This is **_Lance_**, and I am assigned to review your codes if it follows to the [coding guidelines](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.p). So here are some of my observations:

1. IDs should be written in [snake case.](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5)

https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/rosario_angelica/index.html#L15

https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/rosario_angelica/index.html#L26

So far, the website of @RosarioAngelica is great! I especially love the utilization of border-radius and box-shadows in the page. Here are some recommendations for the enhancement of your site:

1. The **color contrasts** of the texts and backgrounds can be improve, for better readability. I recommend using a [Color Contrast Checker](https://coolors.co/contrast-checker/112a46-acc8e5) to get the perfect color scheme for your site.

2. Balancing the **whitespaces**, by utilizing the paddings and margins, can be helpful in improving the readability and give the content room to breathe.

3. **Consistency** in design elements such as colors, fonts, spacing, sizes, and alignment throughout the page is great to be observed.

4. You can put all the images you have used inside a folder to make your directory **organized** and to make it easier to locate files.

**Comment by RosarioAngelica** [comment]
Thank you po!
