### ISSUE TITLE
Code Review for Ilagan

### ISSUE THREAD

**Issue by Monroy-JeffCarl** [PUP-BSIT/ex9-sixth_sense#2]
Hi, Andrei Jireh! I am Jeff and I am tasked to review your codes for this exercise. Thank you!

**Comment by Monroy-JeffCarl** [comment]
There is an empty paragraph element in this code. You can remove it if there's no content intended for it.
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/ilagan_andreijireh/index.html#L30

**Comment by Monroy-JeffCarl** [comment]
To make your code more readable, you can add space between`</div>` and `<div>` here.
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/ilagan_andreijireh/index.html#L73-L74

**Comment by Monroy-JeffCarl** [comment]
If you want to make your code shorter, I suggest grouping the list (`<li>`) in a single unordered list (`<ul>`) element. Just like what you did on your **My interests and hobbies**. You can use the code below for your reference.
```
<ul>
    <li><a href="work.html">Work 1</a></li>
    <li><a href="work.html">Work 2</a></li>
    <li><a href="work.html">Work 3</a></li>
    <li><a href="work.html">Work 4</a></li>
    <li><a href="work.html">Work 5</a></li>
    <li><a href="work.html">Work 6</a></li>
</ul>
```

https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/ilagan_andreijireh/index.html#L31-L53

**Comment by Monroy-JeffCarl** [comment]
Consider adding margin or padding to the **Contact Me** container to create space on the left side.
![image](https://github.com/PUP-BSIT/ex9-sixth_sense/assets/146610699/8ff85188-ffde-435a-b288-0764f0ef26c5)

**Comment by Monroy-JeffCarl** [comment]
In the **My interests and hobbies** and **My Works** containers, if you want to make the `<ul>` centered, consider adding the code below to your **style.css**. There is an auto padding in every `<ul>`, so modifying the padding makes them centered.
```
ul {
  padding-left: 0;
}
```
![image](https://github.com/PUP-BSIT/ex9-sixth_sense/assets/146610699/e3eac52d-a23b-4890-967c-3b2d665c5d18)

**Comment by Monroy-JeffCarl** [comment]
I think that's all for now. Your code looks good overall, with no major errors. Also, the mobile responsiveness is working fine. Keep up the good work, Andrei Jireh! 😊

**Comment by IlaganJireh** [comment]
Hello, I've changed the errors in my code. Thank you!
