### ISSUE TITLE
Code Review for Escuro

### ISSUE THREAD

**Issue by Castro-AizaMae** [PUP-BSIT/ex9-sixth_sense#3]
> **Hi, @Escuro-JohnDenielL , this is some of my observation to your codes for this exercise.**

- **Observe proper indentation.**

1. https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/escuro_johndeniel/index.html#L3C1-L9C9
2. https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/escuro_johndeniel/index.html#L95C1-L96C8

- **Consider adding line spaces between code or code groups for readability.**

https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/escuro_johndeniel/index.html#L10C1-L62C17

- **Exceeds 80 column**

https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/escuro_johndeniel/index.html#L70

>  **I recently had the opportunity to explore your website, and I must say that I’m impressed how good and neat your website is. While I love what you’ve done so far, I’d like to offer a few suggestions that might enhance your website. :)**

 
**_- Consider maintaining consistent box sizes, fonts, text alignment, and list positioning across the site._**

![Screenshot 2024-04-16 191218](https://github.com/PUP-BSIT/ex9-sixth_sense/assets/146600874/d4e2a74a-1781-4998-bea8-1e03f26f9538) 

![Screenshot 2024-04-16 192041](https://github.com/PUP-BSIT/ex9-sixth_sense/assets/146600874/452b0050-09d1-41fc-9056-6e12c4cd7274)

**_- Place the checkbox next to the text rather than below of it. This adjustment would make navigation more intuitive for other users. And also it is better to position the labels to the left side of your website._**

![Screenshot 2024-04-16 164248](https://github.com/PUP-BSIT/ex9-sixth_sense/assets/146600874/541c1e94-feda-4d28-9872-cf00d77286ff)

**Comment by Escuro-JohnDenielL** [comment]
Thank you!
