### ISSUE TITLE
Code Review for Trinidad

### ISSUE THREAD

**Issue by Ayacocho-KylieRoss** [PUP-BSIT/ex9-sixth_sense#4]
Hi, @Trinidad-KianLee! I am **_Ky_** and I was assigned to review your files and website for your exercise 9.

**1. The `<p>` tag is nested within a `<h2>` tag in the interest and works section. It might be better to have the `<h2>` tag directly wrap the `<ul>` or `<ol>` element. Here's what it should look like:**

```
<h2>My Interests and hobbies</h2>
<ul>
  <li>Watching movies</li>
  <li>Playing Games</li>
  <li>Walking</li>
  <li>Horror Documentaries</li>
  <li>Watching tutorial videos</li>
</ul>
```
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/trinidad_kianlee/trinidad_kianlee.html#L15-L24

**2. Separate your CSS block with a single space** 
(https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35)
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/trinidad_kianlee/trinidad_style.css#L55-L65

**I explored your website and I like your theme for it. Here are a few suggestions I would like to add:**

**1. Try balancing your color palettes**

- Your website is quite hard to read due to the contrast. You can use a [Contrast Checker](https://coolors.co/contrast-checker) to check if your colors can be readable. You can also look for color palettes at [Color Hunt](https://colorhunt.co/).

**2. Adding a max width**

- You can improve responsiveness by using a wider range for different screen sizes (ex. max-width: 768px for tablets).
(https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g28d48e53e08_0_0)

**3. Try using the Modal Effect for the gallery**
- It might be better to implement a [Modal Effect](https://www.w3schools.com/howto/howto_css_modal_images.asp) when clicking the image so that it could be a more user-friendly experience.

**4. Organize your files**
- It's best to put your image files in a separate folder so that it won't be clutter inside your directory.

**Comment by Trinidad-KianLee** [comment]
Thank you!
