### ISSUE TITLE
Code Review for Gasta

### ISSUE THREAD

**Issue by Pascual-ArzelFernando** [PUP-BSIT/ex9-sixth_sense#5]
Hello Marc Oliver, I'm Arzel from BSIT 3-1 and this is my Code Review and suggestions for you :)

1. Observe Proper Indentation:
![image](https://github.com/PUP-BSIT/ex9-sixth_sense/assets/146618338/ad28ce60-d3d5-459f-9743-41f72b6cac78)
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/gasta_marcoliver/index.html#L81-L119
- You can configure the tab/space size to 4 or simply use the extension Prettier for proper indentation and spacing when you are coding. 

2. Instead of using an image [(db.jpg)](https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/gasta_marcoliver/db.jpg) for the background of the header you can simply change its background color into to this one.
`background-color: rgb(2, 0, 65);`

3. If you wish to shorten your code use one line only for the ordered list, you can convert this ordered list from the code structure of your unordered list:

Ordered List
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/gasta_marcoliver/index.html#L29-L41
Unordered List
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/gasta_marcoliver/index.html#L19-L24

4. When Styling always do a mobile first approach and start with small mobile and so on from our [guidelines](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g28d48e53e08_0_0).

@media (max-width: 320px) {...}
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/gasta_marcoliver/styles.css#L148-L152

5. You can insert your images in one folder for better locating of files.
6. You can use [Lighthouse ](https://www.youtube.com/watch?v=VyaHwvPWuZU)to check the performance of your website and also you can give it a try to use the [Color Contrast Checker](https://coolors.co/contrast-checker/112a46-acc8e5) for better color pallet you might use in the future.

Thanks and Goodluck <3

**Comment by Gasta-Marc-Oliver** [comment]
Thank you
