### ISSUE TITLE
Code Review For Armedilla

### ISSUE THREAD

**Issue by Pascual-ArzelFernando** [PUP-BSIT/ex9-sixth_sense#6]
Hello Alliah, I'm Arzel from BSIT 3-1 and this is my Code Review and suggestions for you :)

1. Kindly Observe Proper [Indentation](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50):
![image](https://github.com/PUP-BSIT/ex9-sixth_sense/assets/146618338/c7f1d0e1-44ab-4848-aa4a-dedf9a441783)
- While coding practice to double check the different beginning and end of different `<div></div>`
- You can configure the tab/space size to 4 or simply use the extension Prettier for proper indentation and spacing when you are coding. 

2. If you don't need this `<div>` you can just delete this because it doesn't have its ending tag.
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/armedilla_alliyah_samantha/index.html#L96

3. I noticed that this is just the same size of media, you can change this 2nd one to other media size or you can just merged this if you intent to use it once.
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/armedilla_alliyah_samantha/mystyle.css#L74-L114

4. But when you are just styling it, always do a mobile first approach and start with small mobile and so on from our [guidelines](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g28d48e53e08_0_0).

5. You can consider adding margin or padding to the Contact Me container to create space on the left side of each form labels.
![image](https://github.com/PUP-BSIT/ex9-sixth_sense/assets/146618338/88c1c96f-1e70-4b0d-9931-871974dcc82e)

6. You can insert your images in one folder for better locating of files.
7. You can use [Lighthouse ](https://www.youtube.com/watch?v=VyaHwvPWuZU)to check the performance of your website, and also your website color is adorable. However you can give it a try to use the [Color Contrast Checker](https://coolors.co/contrast-checker/112a46-acc8e5) for better color pallet you might use in the future.

Thanks and Goodluck <3

**Comment by armedillaalliyah** [comment]
Thank you!
