### ISSUE TITLE
Additional Reviews

### ISSUE THREAD

**Issue by Ayacocho-KylieRoss** [PUP-BSIT/ex9-sixth_sense#7]
**1. This should only have 80 cols**
(https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0)
https://github.com/PUP-BSIT/ex9-sixth_sense/blob/aea3177f5631dfc8ba91e7ed3acfa28f6cb8e796/index.css#L26
- If you need a guide such as a vertical ruler in your VS Code workspace, here is a tutorial on how to add a vertical ruler so for your next exercises it won't be a problem to see if you exceed.
[Vertical Ruler for Visual Studio Tutorial](https://levelup.gitconnected.com/do-you-know-about-rulers-in-visual-studio-code-f754b221a135)
![Screenshot 2024-04-16 222723](https://github.com/PUP-BSIT/ex9-sixth_sense/assets/83821201/9ad29d2c-8ef4-4e43-a07a-92837b359dbb)

**2. Git Commit Messages**
(https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1zoWNEdakiMRw9POkIZ1Gr0knMwsuxhqS0I5Zl5sAWwuhYun9OH4WS7Jo#slide=id.g28d48e53e08_0_21)
- Next time, be specific about what changes you've made to your files in your commits.
- ex. _"Add Contact Forms", "Update index.html file", "Change Images"_
![Screenshot 2024-04-16 222550](https://github.com/PUP-BSIT/ex9-sixth_sense/assets/83821201/661c5c6e-5017-4019-a264-1f4dd90fe8ba)

**Comment by Trinidad-KianLee** [comment]
Thank you!
